services:
  hichi:
    image: python3-serial
    container_name: hichi-ir-ttl
    restart: unless-stopped
    ports:
      - "9400:9400"
    networks:
      - database
    environment:
      - PROMETHEUS_PORT=9400
    volumes:
      - type: bind
        source: ./hichi-bridge.py
        target: /app/app.py
        read_only: true
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    command: python -u /app/app.py

networks:
  database:
    name: database
    external: true
